





:class:`FieldContainerPlottingError`
====================================

.. py:exception:: ansys.dpf.core.errors.FieldContainerPlottingError(msg=_FIELD_CONTAINER_PLOTTING_MSG)

   Bases: :py:obj:`ValueError`


   Error raised when attempting to plot a fields_container containing multiple fields.




Import detail
-------------

.. code-block:: python

    from ansys.dpf.core.errors import FieldContainerPlottingError





